### ISSUE TITLE
Error on action run

### ISSUE THREAD

**Issue by vrom911** [svenstaro/upx-action#7] opened 2020-07-09 11:46 UTC
Thank you a lot for this action! This is a very useful one.

I tried to use it for the releasing workflow, but unfortunately, I got the error, which I can't understand the nature of:

```
Run svenstaro/upx-action@v2
internal/modules/cjs/loader.js:1025
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/runner/work/_actions/svenstaro/upx-action/v2/dist/binding-v4.0.6-node-v72-linux-x64/lzma_native.node, 1): no suitable image found.  Did find:
	/Users/runner/work/_actions/svenstaro/upx-action/v2/dist/binding-v4.0.6-node-v72-linux-x64/lzma_native.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/runner/work/_actions/svenstaro/upx-action/v2/dist/binding-v4.0.6-node-v72-linux-x64/lzma_native.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/runner/work/_actions/svenstaro/upx-action/v2/dist/index.js:24701:18)
    at __webpack_require__ (/Users/runner/work/_actions/svenstaro/upx-action/v2/dist/index.js:24:31)
    at /Users/runner/work/_actions/svenstaro/upx-action/v2/dist/index.js:29883:14
    at Object.<anonymous> (/Users/runner/work/_actions/svenstaro/upx-action/v2/dist/index.js:30467:3)
    at __webpack_require__ (/Users/runner/work/_actions/svenstaro/upx-action/v2/dist/index.js:24:31)
```

Hope you can help me with that :slightly_smiling_face: 

Oh, and the workflow is here: https://github.com/kowainik/stan/runs/853748578?check_suite_focus=true

**Comment by svenstaro** [comment] 2020-07-18 21:26
I made a test to reproduce this: https://github.com/svenstaro/upx-action/runs/885679374?check_suite_focus=true

Sorry, this should never happen. It's probably due to ncc and the native dependency. I'll fix it somehow.

**Comment by svenstaro** [comment] 2020-07-19 11:02
Should be fixed now, please check.

**Closed as completed** 2020-07-26 06:15 UTC

**Comment by vrom911** [comment] 2020-07-27 13:56
Perfect! Thank you so much 👍🏼
